### ISSUE TITLE
CVE-2016-5349

### ISSUE THREAD

**Issue by hahnjo** [derfelot/discussion#12]
To restore encryption functionality, I had to temporarily revert the four commits fixing CVE-2016-5349 (see #11).

We should either have a look at them again or decide to skip them.

**Comment by Micha-Btz** [comment]
It seems that this also solve the problem with different display types. https://forum.xda-developers.com/showpost.php?p=73060388&postcount=130

I would say leave it out seems the backport makes more trouble as solves problems.

**Comment by hahnjo** [comment]
Hmm, I can't download the provided log files so I don't see a proof that this is related?

**Comment by Micha-Btz** [comment]
I also can't. But if I'm right the diff between the June and the cve rom was only this patch.

**Comment by MSe1969** [comment]
Just for completeness: There is also another difference between June and -cve, but that is not relevant (otherwise the folks would complain now): LockClock, Trebuchet, SetupWizard and Settings (rebrand, remove Google lib, remove tracking)

From a pragmatic point of view:
- Revertig the commits fixed issues
- No CM/LOS 3.4.x kernel had this CVE patched
>> To me it sounds we shouldn't apply the patch...
(No reason to close this issue immediately, but my point of view)

**Comment by Micha-Btz** [comment]
I think we can close this as unaffected since fairfone, lge, htc and lenovo are marked as unaffected in cve.lineageos.org. OK?

**Comment by MSe1969** [comment]
Okay, I'll close it now.
