### ISSUE TITLE
CVE-2016-5129 (left-over from April ASB)

### ISSUE THREAD

**Issue by MSe1969** [derfelot/discussion#4]
Little bit nasty: 
Google has flagged for this one, that they didn't update AOSP 5.x and below. 
However - if you look at this more carefully, it indeed IS relevant - however, between LP and MM, the chromium stuff was significantly reworked from "compile from scratch" to "provide a prebuilt webview.apk" and thus, the repository was reworked.

"v8" in MM is located in 'external/v8', whilst in LP and before, it is located under 'external/chromium_org/v8' (if you ask me, that is the only reason why they didn't flag it as relevant for LP - the coding however fits).

The upstream patch is here:
https://chromium.googlesource.com/v8/v8.git/+/b4b9377b674f84d21c12e1d6986c5b1ecffb7b3f

So I would need a fork of AOSP 'platform/external/chromium_org/v8' to be able to work on this.

**Comment by Micha-Btz** [comment]
Now we have the fork will you commit the fix @MSe1969 or should I do?

**Comment by MSe1969** [comment]
Hi @Micha-Btz , as I did it already before (see: https://review.lineageos.org/#/c/174776/ - currently in review), it might be easier if I do it. I anyhow am trying something with regards to webview, which is meanwhile more than outdated (our chromium main version is 39, whilst 58 is 'state of the art'), which is related - will keep you guys posted.
@derfelot - please let me know, when you are available, so I can transfer the fork to here.

**Comment by MSe1969** [comment]
Hi @derfelot and @Micha-Btz - 
Okay, my first tests look promising. So here comes my proposal - it consists of three parts:

1. **Patch/Fix V8 (the original topic of this issue)** 
This is definitely necessary and I'll do it now

2. **The webview.apk of our build is really outdated (and thus most probably insecure!)**
When we build, it compiles release 39 from scratch, which is also time-consuming during build.
Starting with Android 6, webview.apk comes as a prebuild. I've included the cm-14.1 repo and set property PRODUCT_PREBUILT_WEBVIEWCHROMIUM=yes for the build (right now in build script as export env variable, later to be added to vendor/cm or device config), which skips the webview compilation and uses the referred prebuild.
As a result, webview.apk is on the current release 58 and all apps making use of it (most apps offering to show internet content without actually being a browser make use of webview) are more secure.

3. **Replace the old 'Browser' app**
The old browser app is also more than outdated (and assumed insecure). Including the new 'Jelly' browser from LineageOS is unfortunately NOT an option, as Jelly requires SDK 23 (Android 6).
_Alternative 1:_
Include Gello from cm-13.0 - less outdated (chromium rel. 42), but still outdated - at least better than the original browser app.  
_Alternative 2:_
I've come across this chromium custom build based on CodeAurora via F-Droid: 
https://github.com/bamless/chromium-swe-builds (the repo README contains some links to CAF and XDA) Could that be an option?
_Alternative 3:_
Proposals from your side?

What is your opinion on this?
Regards, M.

**Comment by MSe1969** [comment]
Have implemented topic 1 (CVE-2016-5129 in v8) and topic 2 (webview.apk rel. 58). 
However, struggling with including the Chromium SWE as prebuilt system app (works fine as user app, but not as system app - need to further evaluate. Seems to be related to included libraries in apk, which seem to be unpacked as well during build).

**Comment by derfelot** [comment]
Hi,

so should I just fork the platform/external/chromium_org/v8 from you and add you guys?

As for the rest:

2. That's good, but I also wouldn't have seen it as much of a problem. You could just remove the pre-installed webview and grab the updated one from play store. You can even run both side-by-side and select the one you want to use in dev options (IIRC).

3. That CAF browser would be a good alternative I think.

As for the kernel: yes, our version seems extremely outdated. However, most of the important and relevant things have been included. So its not really a 3.4.0 kernel at all. This also causes some big problems to bump it to .113 however. I've spent hours at one point trying to do it in two different ways. The first was to grab the patch file from kernel.org (3.4.0 --> 3.4.113), split it into individual patches and apply them. Those that created conflicts, however, were a pain to resolve. So I gave up on it. The other way I tried to do it, was to download the complete 3.4.113 kernel and merge the required additional drivers, defconfigs, etc. into it (diffing the two kernel sources basically). It's quite a big task and I eventually gave up on it because this took ages as well. If one of you feels up to it, I would suggest the second method :) Afterwards, it'd be good to double check that all important security fixes are still in there of course....

**Comment by MSe1969** [comment]
rgd. the fork: whatever is easier - I can transfer the ownership of "my" fork to you, or you make a fork - you decide... :)

**Comment by derfelot** [comment]
so i guess you have merged everything into the cm-12.1 branches, correct? Is it safe to remove the test ones? Anything else I missed doing?

Sorry, I'm still really busy with work and probably still will be till the end of this week. ;)

**Comment by MSe1969** [comment]
yes, all merged and test branches already purged. 
currently three new test branches: 
- android_build (because that one we need every month :) - but even with cm-12.1), 
- android_vendor_cm (I am working on that one)
- and v8, which you've just forked

**Comment by derfelot** [comment]
So nothing left for me to do then :p 

Let's see how many hundred patches coming up for June then...

**Comment by MSe1969** [comment]
right :) - have just changed the local manifest to point v8 to 'derfelot' instread of 'MSe1969'
Yeah, curious to see June.

**Comment by Micha-Btz** [comment]
when you already have tried to bump the kernel to the latest version I don't think I have more luck on this.
Maybe we should only apply patches that are work out of the box  and skip this ones that would not apply cleanly. 
@MSe1969 I think include the browser as user app is enough so the user can easily remove this one if it is not wanted. The move to system app has no benefit I think.

Maybe we should create a separate issue for the kernel and close this one since it is fixed.

**Comment by MSe1969** [comment]
OK, I have merged CVE-2016-5129 fix and the prebuilt webview.apk into the stable release branch cm-12.1. I'll open a new issue for the Browser replacement and close this one.

@Micha-Btz - as far as I know, there is no possibility to deliver user apps in an OTA zip. The concept of OTA updates is, that the /system partition is wiped and newly flashed, whilst the /data partition remains untouched. I think stock ROMs providing user apps have a built-in script to install them during first startup. The OTA zip contains a userdata.img, but that is ONLY flashed, if there is nothing in /data at all. So all apps shipped with an OTA flashable ZIP are system apps (you can only specify whether "ordinary" system apps (/system/app) or privileged platform apps (/system/priv-app).
