### ISSUE TITLE
kernel version outdated

### ISSUE THREAD

**Issue by Micha-Btz** [derfelot/discussion#5]
We should try to patch the kernel as far as possible to the latest version 3.4.113 maybe we can use some of
https://review.lineageos.org/#/c/174440/
Will give it a try after Pfingsten.

**Comment by MSe1969** [comment]
Very desired, but difficult (as already mentioned). Btw, the referred LOS review topic 'bacon-3.4.113' with the huge lot of patches assigned simply adresses the changes from sublevel 112 to 113 ...

**Comment by MSe1969** [comment]
Hi @Micha-Btz  @derfelot  - you may have already noticed this new LOS feature:
https://cve.lineageos.org/android_kernel_sony_msm8974

It is however NOT the result of an automated repo scan, but the result of a manual update by the device maintainer, so I don't know, whether this is accurate or maybe not (e.g, because the respective maintainers did not really update it, yet - it for sure doesn't reflect derfelot's work since September 2016; there are even LOS kernels listed with 0%) - however, this could be used as a starting point for us to step-by-step verify and add any missing patch from the previous years, if not yet done and if applicable.

**Comment by derfelot** [comment]
You mean since April 2016 :p

Anyhow, yeah that stuff is purely manual it seems. Unfortunately, there is no links to the respective commits though. I do have a (semi-) complete list of all the CVE's I've fixed or checked that the fix is already included though. For sveral fixes issues, I am unsure of the CVE #. Still not a bad idea to double check.

[cve.txt](https://github.com/derfelot/discussion/files/1048660/cve.txt)

**Comment by MSe1969** [comment]
On that LOS CVE site, if you click on each CVE number, a popup opens with the link to the CVE DB and link(s) to the respective commits. I've done a little spot check, the oldest ones ARE patched in our kernel, so I really assume, that whoever device maintainer feels responsible has to go through that list first and mark the entries accordingly.

**Comment by hahnjo** [comment]
I'm trying to take care of this and patch to 3.4.113. You can view my progress at my fork: https://github.com/hahnjo/android_kernel_sony_msm8974/commits/kernel-3.4

**Comment by Micha-Btz** [comment]
great work so far @hahnjo 

I don't think that the LOS cvs Page are usefull for us and also @derfelot has patched most of them.
I will take a look at the page and derfs cvs.txt to see if we missed something and for the new ones we should do it as before and list which one is not fixed be us in the monthly issue.

**Comment by Micha-Btz** [comment]
moin,
yesterday I compare the LOS cvs page and the cvs.txt from @derfelot 
and the file contains all cve that are missed. I don't think all of this is really open but we should compare the 
code. Probably the kernel patches fixes some of them too.

[missed-cvs.txt](https://github.com/derfelot/discussion/files/1056963/missed-cvs.txt)

@hahnjo I would wait until you patched the kernel to the latest sublevel to avoid merge problems. Then I would take a look of the seperate CVE.

**Comment by hahnjo** [comment]
@Micha-Btz thanks for waiting!

We might want to add CVE-2016-1583: This had been fixed but I had some merge conflicts with that patch. Maybe just double check that the fix is still correct ;-)

**Comment by Micha-Btz** [comment]
@hahnjo 
are you finished? Then please PR this to derf's cm-12.1-test branch. Then we should test if a build is successful and after that we can look at the single CVE.
I will take a look at CVE-2016-1583 too.

**Comment by hahnjo** [comment]
@Micha-Btz depends on the definition of `finished`: Yes, it compiles and it starts to boot. However, it hangs and bootloops after a while. Investigation pending...

**Comment by Micha-Btz** [comment]
sad. bootloop's are difficult to debug I think. If you need some help tell me how to debug and I will take a look.

**Comment by hahnjo** [comment]
I have to see if I can get a log right before it reboots.

Otherwise there is a limited number of merges where something could have gone wrong. Once the offending one is found, I can either look at the changes and conflicts or redo that merge one single tag after another. This will hopefully guide me to the wrong change. Still plenty of ideas here ;-)

**Comment by Micha-Btz** [comment]
ok, lots of luck and patience to you :-)

**Comment by hahnjo** [comment]
Hehe, that was easy: https://github.com/derfelot/android_kernel_sony_msm8974/pull/1/commits/46083c47949758491c9055041fa994ca1f8840f9 Maybe I was a bit tired already yesterday evening ;-)

Anyway, here we go: https://github.com/derfelot/android_kernel_sony_msm8974/pull/1 (there was no cm-12.1-test and I don't yet have permissions to create one). Please give it a try!

**Comment by Micha-Btz** [comment]
I have added CVE-2016-1583 after merging the PR without problems. I will make a test build and if it works I will commit to the repo.

**Comment by hahnjo** [comment]
@Micha-Btz which one, https://bugzilla.redhat.com/show_bug.cgi?id=1344721 lists three patches?

**Comment by Micha-Btz** [comment]
@hahnjo I seems tricky. My build doesn't compile.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2f36db71009304b3f0b95afacd8eba1f9f046b87 is in and the other two patches doesn't fit our code.
Also I found this one https://review.lineageos.org/#/c/165178/ which aplly cleanly but I don't know how does it fit to the three patches itself. Strange for me.

**Comment by derfelot** [comment]
@hahnjo I've sent you an invite to become a collaborator for the kernel. If you need access to any other repos, give me a shoutout.

**Comment by hahnjo** [comment]
@Micha-Btz your commit to `cm-12.1-june` is wrong: The code is already there, just below the lines you added. It won't compile because of the redifinition of `file`.

The code will go away anyway with 3.4.113 with commit https://github.com/derfelot/android_kernel_sony_msm8974/commit/068478a54bcd742e34b80f316472f3b06cacd8c6

**Comment by MSe1969** [comment]
With regards to the 3.4.113 build - two items to be considered:

1. Please make sure, that below commit does not get lost (LineageOS 'su hide' patch):
https://github.com/derfelot/android_kernel_sony_msm8974/commit/beb7c2696697311b4507d9dba805b89e6272b43e

2. We should include also the following patch 
https://github.com/torvalds/linux/commit/3e21f4af170bebf47c187c1ff8bf155583c9f3b1

References: 
https://alephsecurity.com/vulns/aleph-2017023 - CVE-2017-1000363 (not yet in cve.mitre.org)
https://www.xda-developers.com/moto-g4-moto-g5-aboot-vulnerability-grants-a-root-shell-patched-in-mays-security-update/

Background:
A vulnerability in certain motorola bootloaders can be exploited, and this patch closes the underlying kernel part of the vuln, as the possibility cannot be excluded, that other bootloaders might be attackable as well.

**Comment by Micha-Btz** [comment]
Great so if I'm right we only need one patch from the june branch to the test branch and we can test the kernel 3.4.113. I will do a local build tonight to test this. And then I will take a look at the missed-cve.txt.

The su hide patch is in and there are no merge conflicts so I think it's ok.
CVE-2016-10277: Include this patch should not be a problem. I'm not sure if we are really affected since we not using the aboot loader. I will test this to.

**Comment by hahnjo** [comment]
@Micha-Btz I think we can just merge `cm-12.1` to `cm-12.1-test` once we promoted `cm-12.1-june`.

Regarding testing: I'm thinking about providing a flashable zip and asking in the xda thread for everyone interested to test. We could provide a "revert" zip to go back to the older kernel, just in case something goes wrong. What do you think?

**Comment by Micha-Btz** [comment]
Let's do so. But before we offer a flashable zip we should consider that the phone boot correctly.
For now I haven't done a install test, did you?

**Comment by hahnjo** [comment]
Yes, running since Friday without problems, subtracting the time when I tested the patch in `cm-12.1-june`...

**Comment by Micha-Btz** [comment]
Ok, then it should work. It's a goog idea to have more tester.

**Comment by hahnjo** [comment]
I think we should also apply these three patches, the latter two are fixes for the first commit:
* https://github.com/LineageOS/lge-kernel-mako/commit/5e0765757d92fc747f3b8a44b85821e8966c333e
* https://github.com/LineageOS/lge-kernel-mako/commit/383245ed97087e02651e28a7a2ecf0f49fa363fe
* https://github.com/LineageOS/lge-kernel-mako/commit/3d232fa82d96e9a700715eee05511ed33c2b5c6d

Just let me know if you want me to apply them once you have pushed.

**Comment by Micha-Btz** [comment]
No problems so far with my build. I will commit the patch today.
@hahnjo You can commit this patches I also think it would be a good thing to have.

**Comment by Micha-Btz** [comment]
I'm done with the patch, @hahnjo you can commit.

**Comment by hahnjo** [comment]
Ok. In addition to the ext4 patches I linked above, do we have other patches to include? Should I otherwise try to put this in a zip and post it for testing?

**Comment by Micha-Btz** [comment]
Now I will go trough the list of missed-cve to see which one we need and which one we have.
Will see if there are patches to apply.

**Comment by Micha-Btz** [comment]
- CVE-2012-6704 fixed
- CVE-2013-2015 fixed
- CVE-2013-4312 fixed
- CVE-2014-0206 seems to be not belong to kernel 3.4 intoduced in kernel 3.10
- CVE-2014-1739 fixed
- CVE-2014-2706 fixed
- CVE-2014-3145 fixed
- CVE-2014-9922 fix for sdcardfs which we don't use in cm-12.1
- CVE-2014-9940 doesn't fit our code, 2nd opinion needed.
- CVE-2014-0565 belong to Adobe!?!
- CVE-2014-0570 belong to Adobe!?!
- CVE-2014-0571 belong to Adobe!?!
- CVE-2015-5706 seems to affect only kernels 3.11+
- CVE-2015-8830 fixed
- CVE-2015-9004 fixed
Would be great if someone can take a look at CVE-2014-9940. Will go on with 2016.

**Comment by Micha-Btz** [comment]
- CVE-2016-0805 fixed
- CVE-2016-0823 fixed
- CVE-2016-10088 fixed
- CVE-2016-10153 fixed
- CVE-2016-10154 seems to affect only kernels 4.9+
- CVE-2016-10229 fixed
- CVE-2016-10230 fixed
- CVE-2016-10231 reserved not available yet
- CVE-2016-10232 open, unsure if we are affected, 2nd opinion needed
- CVE-2016-10233 fixed
- CVE-2016-10234 fixed
- CVE-2016-10235 open, fix https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/b4a224cccec0b012ddf510db34e64c272de5a831
- CVE-2016-10236 reserved not available yet
- CVE-2016-10283 open, unsure if we are affected, 2nd opinion needed
- CVE-2016-10285 not applicable - declined May Issue 2017
- CVE-2016-10287 file to be patched does not exist
- CVE-2016-10288 file to be patched does not exist
- CVE-2016-10289 fixed
- CVE-2016-10290 file to be patched does not exist
- CVE-2016-10291 file to be patched does not exist
- CVE-2016-10292 closed source
- CVE-2016-10293 N/A - decision after analysis
- CVE-2016-10294 file to be patched does not exist
- CVE-2016-10295 N/A - decision after analysis
- CVE-2016-10296 file to be patched does not exist
- 
- CVE-2016-2061 open, one file to patch missed, backport? , 2nd opinion needed.
- CVE-2016-2066 open, https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/90254a7e90e0e023f74a60be05434b82f0317ab4
- CVE-2016-2465 open, https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/1d6fca684e4a9da702975761659182839bbba107
- CVE-2016-2466 closed source binary
- CVE-2016-2467 closed source binary
- CVE-2016-2474 closed source binary
- CVE-2016-2475 closed source binary
- CVE-2016-2488 closed source binary
- CVE-2016-3070 open, https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/0126befdd890db5e8fcea417f1d77bac29164077
- CVE-2016-3137 open,https://github.com/LineageOS/lge-kernel-mako/commit/56ee0998b255afb9ad0d051e2ce5780e94086505
- CVE-2016-3809 fixed
- CVE-2016-4486 fixed
- CVE-2016-4794 seems to affect only kernels 4.6
- CVE-2016-5347 open, https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/c184db58edc42f59c8fcdfd6399c59c230651572
- CVE-2016-5349 <NOT (YET) IMPLEMENTED: not all files to be patched exist; backport or N/A???>
- CVE-2016-5853 file to be patched does not exist
- CVE-2016-5854 file to be patched does not exist
- CVE-2016-5855 file to be patched does not exist
- CVE-2016-5858 implemented (1 of 2)
- CVE-2016-5859 N/A - decision after analysis
- CVE-2016-5860 file to be patched does not exist
- CVE-2016-5862 N/A - fix is for MSM8996 Kernels, ours is MSM8974
- CVE-2016-5867 N/A - decision after analysis
- CVE-2016-5868 file to be patched does not exist
- CVE-2016-5870 fixed
- CVE-2016-6751 backport needed?, 2nd opinion needed
- CVE-2016-6753 fixed
- CVE-2016-7042 fixed
- CVE-2016-8479 code doesn't fit, 2nd opinion needed
- CVE-2016-8483 file to be patched does not exist
- CVE-2016-8650 fixed
- CVE-2016-8655 fixed
- CVE-2016-9120 open, https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/458059fbc31b7276be266035e94e6e0b41427327
- CVE-2016-9191 seems to affect only kernels 4.8.11
- CVE-2016-9604 opn,https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/c57a647b6063d36a2a0e995afed5e7b74683a5e3
- CVE-2016-9754 fixed
- CVE-2016-9794 fixed

**Comment by Micha-Btz** [comment]
- CVE-2017-0404 closed source binary patch available https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/b6b87ebf012532019e5a72b55d8b105002a721be
- CVE-2017-0432 MediaTek driver
- CVE-2017-0433 closed source
- CVE-2017-0434 closed source
- CVE-2017-0435 maybe we should remove Ultrasound like https://review.lineageos.org/#/c/177183/
- CVE-2017-0436 maybe we should remove Ultrasound like https://review.lineageos.org/#/c/177183/
- CVE-2017-0437 Elevation of privilege vulnerability in Qualcomm Wi-Fi driver
- CVE-2017-0438 Elevation of privilege vulnerability in Qualcomm Wi-Fi driver
- CVE-2017-0439 Elevation of privilege vulnerability in Qualcomm Wi-Fi driver
- CVE-2017-0440 Elevation of privilege vulnerability in Qualcomm Wi-Fi driver
- CVE-2017-0441 Elevation of privilege vulnerability in Qualcomm Wi-Fi driver
- CVE-2017-0442 Elevation of privilege vulnerability in Qualcomm Wi-Fi driver
- CVE-2017-0443 Elevation of privilege vulnerability in Qualcomm Wi-Fi driver
- CVE-2017-0444 vulnerability in Realtek sound driver
- CVE-2017-0445 N/A HTC touchscreen driver
- CVE-2017-0446 N/A HTC touchscreen driver
- CVE-2017-0447 N/A HTC touchscreen driver
- CVE-2017-0448 N/A NVIDIA video driver
- CVE-2017-0449 Broadcom Wi-Fi driver
- CVE-2017-0452 closed source
- CVE-2017-0454 file to be patched does not exist
- CVE-2017-0460 file to be patched does not exist
- CVE-2017-0462 file to be patched does not exist
- CVE-2017-0465 declined ASB 05/2017
- CVE-2017-0507 open https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/160a7b8e32be000ec418433afbc25820a4208b8e
- CVE-2017-0516 open https://github.com/LineageOS/android_kernel_lenovo_msm8974/commit/697ef4e308c9033a8f5ca50cab39d90d6232d7a9
- CVE-2017-0535 closed source HTC Sound driver
- CVE-2017-0537 file to be patched does not exist
- CVE-2017-0564 file to be patched does not exist
- CVE-2017-0576 fixed
- CVE-2017-0583 N/A for amami: Fixes an ARM64 issue
- CVE-2017-0631 N/A - decision after analysis
- CVE-2017-0632 file to be patched does not exist
- CVE-2017-5546 affects only kernel 4.8.x-4.9.5
- CVE-2017-5547 affects only kernel 4.9.x-4.9.5
- CVE-2017-5550 file to be patched does not exist
- CVE-2017-5551 open, https://github.com/LineageOS/android_kernel_cyanogen_msm8916/commit/4594014df25bd125df6033cc99e2c2ee3ec93756
- CVE-2017-5897 file to be patched does not exist
- CVE-2017-5972 open, https://github.com/LineageOS/android_kernel_sony_msm8960t/commit/a1847fa92a2c4e132c7ccf2f0c3e67561cfc333e
- CVE-2017-5986 open, https://github.com/LineageOS/lge-kernel-mako/commit/04861a0e2f91e9e25a8af550dba30e563337e1a1
- CVE-2017-6074 open, https://github.com/LineageOS/android_kernel_htc_msm8960/commit/b65af4c8fd1110d8c68a68dfc95b4fbad5d1cf8e
- CVE-2017-6214 open, https://github.com/LineageOS/lge-kernel-mako/commit/0dc81c432bf5e839351e4e3ce41296a7c597ae43
- CVE-2017-6345 open,maybe https://review.lineageos.org/#/c/172205/ fix it
- CVE-2017-6346 unsure, 2nd opinion needed
- CVE-2017-6347 unsure, maybe backport needed, 2nd opinion needed
- CVE-2017-6348 open, maybe https://review.lineageos.org/#/c/172206/ fixed it
- CVE-2017-6353 open, maybe https://review.lineageos.org/#/c/175239/ fixed it
- CVE-2017-6423 file to be patched does not exist
- CVE-2017-6424 file to be patched does not exist
- CVE-2017-6425 file to be patched does not exist
- CVE-2017-6426 file to be patched does not exist
- CVE-2017-6874 affects only kernel 4.10.2
- CVE-2017-6951 open, https://github.com/LineageOS/android_kernel_sony_msm8x60/commit/85eaed140341e310d665f0942c8804da9fa9d175
- CVE-2017-7184 N/A - decision after analysis
- CVE-2017-7187 open, https://github.com/LineageOS/android_kernel_lge_msm8974/commit/f6cb2616d38ede387e26eeac3de79ec957adfc06
- 				https://github.com/LineageOS/android_kernel_lge_msm8974/commit/3fb0baaaeda9cbbc97e7d561903f2cff6f5f67fa
- 				https://github.com/LineageOS/android_kernel_lge_msm8974/commit/1a7c24ce3b9c8dfc7b102b1bed922a084514e87e
- CVE-2017-7277 open, backport needed?, 2nd opinion needed
- CVE-2017-7308 fixed
- CVE-2017-7374 unsure, 2nd opinion needed, maybe backport
- CVE-2017-7472 open, https://github.com/LineageOS/android_kernel_sony_msm8960t/commit/a3c064f5b9fc5b5f7abfe7be98129142532ef631
- CVE-2017-7495 ext4 bug, backport needed?, 2nd opinion needed
- CVE-2017-7616 open, https://github.com/LineageOS/android_kernel_cyanogen_msm8916/commit/e810ca0ba56fe45c0a07124023b8ac3d06fe2534
- CVE-2017-7618 open, backport needed
- CVE-2017-7889 open, backport needed
- CVE-2017-7979 does not affect stable kernels
- CVE-2017-8244 unsure, 2nd opinion needed, maybe backport
- CVE-2017-8245 file to be patched does not exist
- CVE-2017-8246 fixed
- CVE-2017-8890 fixed
- CVE-2017-9074 open, backport needed, one file missed
- CVE-2017-9075 open, https://github.com/LineageOS/android_kernel_asus_Z00D/commit/cbc6a16c516f512b8be5e7d236e6a719471f1757
- CVE-2017-9076 open, https://github.com/LineageOS/android_kernel_xiaomi_msm8956/commit/635f97a715ca82b04f9c822102c7850eab989eda
- CVE-2017-9077 open, https://github.com/LineageOS/android_kernel_asus_Z00D/commit/8738cb27fd311d72dd476b59b335c8ef5e4f5c93
- CVE-2017-9150 file to be patched does not exist
- CVE-2017-9242 unsure, 2nd opinion needed, maybe backport

so, thats "all" :-)
[missed-cvs.txt](https://github.com/derfelot/discussion/files/1076758/missed-cvs.txt)
Would be great if someone can take a look at the CVE's marked with 2nd opinion needed.
If someone will patch some CVE then go ahead. I will start to patch tomorrow from CVE 2012-2015.
Maybe we should create a new branch for patching this many CVE.

**Comment by hahnjo** [comment]
Wow, thanks for scanning all of them! Unfortunately, I won't be available until Sunday to either patch some CVEs or to take a second look.

Regarding a new branch: I'm not really sure. Do we want to test this in two stages or rather in one together with 3.4.113? I'd favor one stage and hence just using `cm-12.1-test` because this eliminates merge conflicts and maybe includes some already patched CVEs from the upstream developers.

**Comment by Micha-Btz** [comment]
That's not a problem take a look if you have time.

I thought about creating a new branch from cm-12.1-test which we must use as base since the missed-cve.txt is based on that branch. You have fixed some CVE with merging the lastest patches from 3.4.113.
But we can also commit to test branch.

**Comment by Micha-Btz** [comment]
so mostly done, compile test running.

**Comment by Micha-Btz** [comment]
running this kernel now since Friday not problems so far.

**Comment by MSe1969** [comment]
Hi @Micha-Btz @hahnjo ,
is my understanding correct, that now all is finished (= 'ready' to ship) with the 3.4.113 kernel and we all should test it? (First the four of us and then we offer it in XDA for testing purposes)
I would like to start testing it as well :)
Regards, M.

**Comment by Micha-Btz** [comment]
@MSe1969 it's not finished but on a very good way. The kernel run's great with all implemented fixes.
Now it would be great if someone can take a look at the CVE I have marked with 2nd opinion needed or backport required. Which are:
CVE-2014-9940 doesn't fit our code, 2nd opinion needed.
CVE-2016-10232 open, unsure if we are affected, 2nd opinion needed
CVE-2016-2061 open, one file to patch missed, backport? , 2nd opinion needed.
CVE-2016-5349 <NOT (YET) IMPLEMENTED: not all files to be patched exist; backport or N/A???>
CVE-2016-6751 backport needed?, 2nd opinion needed
CVE-2016-8479 code doesn't fit, 2nd opinion needed
CVE-2017-6346 unsure, 2nd opinion needed
CVE-2017-6347 unsure, maybe backport needed, 2nd opinion needed
CVE-2017-7277 open, backport needed?, 2nd opinion needed
CVE-2017-7374 unsure, 2nd opinion needed, maybe backport
CVE-2017-7495 ext4 bug, backport needed?, 2nd opinion needed
CVE-2017-7618 open, backport needed
CVE-2017-7889 open, backport needed
CVE-2017-9074 open, backport needed, one file missed
CVE-2017-9150 file to be patched does not exist
CVE-2017-9242 unsure, 2nd opinion needed, maybe backport
After this was checked again I think we are ready maybe we ship then with the sec patches for July.

**Comment by hahnjo** [comment]
@Micha-Btz Could you for the next time `am` the patches so that we get the original author and commit message?

CVE-2014-9940: regulator_ena_gpio_free has been introduced with Linux 3.10, https://github.com/torvalds/linux/commit/f19b00da8ed37db4e3891fe534fcf3a605a0e562.
CVE-2016-10232: Not affected IMO
CVE-2016-2061: Not affected I think: msm_isp_axi_create_stream gets the index i differently than on 3.18
CVE-2016-6751: Applied patch cleanly? https://source.codeaurora.org/quic/la//kernel/msm-3.18/commit/?id=4907b74ecd5ef8c6d85f1b430f386e381d5b8229
CVE-2016-8479: Our IDs are generated differently, so not affected IMO
CVE-2017-6346: Backported patch: https://github.com/torvalds/linux/commit/d199fab63c11998a602205f7ee7ff7c05c97164b
CVE-2017-6347: Code in question was introduced only in Linux 4.0, https://github.com/torvalds/linux/commit/ad6f939ab193750cc94a265f58e007fb598c97b7
CVE-2017-7277: SOF_TIMESTAMPING_OPT_STATS was introduced in Linux 4.10, https://github.com/torvalds/linux/commit/1c885808e45601b2b6f68b30ac1d999e10b6f606
CVE-2017-7374: Revocation and invalidate not present in our kernel AFAICS
CVE-2017-7495: I think we are not affected...
CVE-2017-7618: The commit that is mentioned to be fixed has been introduced with Linux 3.15, https://github.com/torvalds/linux/commit/ab6bf4e5e5e4
CVE-2017-7889: The patch seems to be related to x86?!? https://github.com/torvalds/linux/commit/a4866aa812518ed1a37d8ea0c881dc946409de94
CVE-2017-9074: Backported patch: https://github.com/torvalds/linux/commit/2423496af35d94a87156b063ea5cedffc10a70a1
CVE-2017-9150: Code in question has been introduced in Linux 3.18, https://github.com/torvalds/linux/commit/cbd357008604925355ae7b54a09137dabb81b580
CVE-2017-9242: Applied patch cleanly?!? https://github.com/torvalds/linux/commit/232cd35d0804cc241eb887bb8d4d9b3b9881c64a

CVE-2016-5349 looks quite massive. Would need to take a second look...

Testing the changes right now, will push afterwards

**Comment by Micha-Btz** [comment]
@hahnjo I know about git am but we have decided that we use the CVE numbers in git commit description. 
But I think use git am were more state of the art. Should we edit the original commit description if the CVE number was not mentioned? @MSe1969 @derfelot ?

If I'm right the only missing CVE is CVE-2016-5349?

**Comment by hahnjo** [comment]
@Micha-Btz To make it easier to read the commit log for CVEs? IMO attribution and meaningful commit messages are equally important. Editing the commit message as done for the stable kernel seems a good idea (`backport to 3.4: adapted context` and the like).

Yes, CVE-2016-5349 is still missing from your list.

**Comment by MSe1969** [comment]
Hi, 
haven't yet used git am; I think however, that (re)using the original commit messages and authorship definitely makes sense. If we can combine this by supplementing the CVE number as well, if missing, that should be the way forward (have done this already, when e.g. backported the ASB's to the original LOS  cm-13.0 code base the last two times)
Regards - M.

**Comment by MSe1969** [comment]
CVE-2016-5349 is really a huge change - we've skipped it in our April ASB, because not all files to be patched exist. My usual "quick check" by copy-pasting into a patch file and running `patch -p1 --dry-run` on it to see whether it can be applied automatically reveals ~70% fails and only ~30% successful patching attempts. That means, that a lot of individual backporting is required - however, I have, looking at the description and what is being patched, the impression that is **IS** relevant . . .

**Comment by hahnjo** [comment]
@MSe1969 yes, I also get the impression that we should apply the patch. Unfortunately, I probably won't find time until mid of July. Do we still want to post test kernels on xda? If yes, we should do so now before the July ASB comes in IMO

**Comment by Micha-Btz** [comment]
I also think we should patch this. Exploits seems not far away. https://github.com/ucsb-seclab/boomerang
After a look at the lineage gerrit no one from the msm8974 devices have that fixed. So the only way I see is to create a backport on our one.
I will give it a try but I think it a little to much for me.

**Comment by MSe1969** [comment]
I agree, we all have used our phones with the new kernel and nobody of us has experienced any weird behavior (this is my experience and from what I have read in this thread, you feel the same); so I also do not really see the necessity to ask folks in XDA for testing.

So let's ship the new kernel, the three google- and tracking-freed apps and the July ASB fixes together and afterwards, let's work on CVE-2016-5349, if you are ok with that approach as well.

**Comment by hahnjo** [comment]
@Micha-Btz @MSe1969 sounds good to me :+1:

**Comment by Micha-Btz** [comment]
I give up on CVE-2016-5349 this is a nightmare. Some files are possible to patch but sometimes the are more than 1500 lines offset an one of the file is on a totally different location.
needed: include/soc/qcom/qseecomi.h
we have arch/arm/mach-msm/include/mach/qseecomi.h

I have done some research but some of our brother boards are:

> https://cve.lineageos.org/android_kernel_htc_msm8974 - unaffected
> https://cve.lineageos.org/android_kernel_lge_msm8974 - unaffected
> https://cve.lineageos.org/android_kernel_motorola_msm8974 - upstram hold
> https://cve.lineageos.org/android_kernel_oneplus_msm8974 - patched
> https://cve.lineageos.org/android_kernel_oppo_msm8974 - patched

I have ask in #lineage-dev but there was no help. I'm unsure if we affected and I haven't seen a patch in oneplus or oppo. So if one of you will take it just do it.

**Comment by MSe1969** [comment]
I can confirm that this patch is not present in any of your listed LOS msm8974 kernels (I did not bother to look at the first two kernels, which state "unaffected" in the CVE tracker):

For the other three kernels, I have looked up the history of the file **drivers/misc/qseecom.c** in the respective LOS github kernel repos to find the commit for CVE-2016-5349 and I did not.
I have also simply searched for the variable `whitelist_support` in the code of qseecom.c, because that variable is present, if the patch was there, and it is not.

So if you ask me, **none** of the LOS msm8974 kernels is patched for CVE-2017-5349!
(I could imagine, that the maintainers for oneplus and oppo simply assumed, that it must have been part of a larger CAF merge of the 3.10 branch, without really looking at the details.)

In CAF, also 3.10 kernels have that fix - it may be worth to look for a diff file in 3.10, which may more "similar" to 3.4 than 3.18. I didn't however find any 3.4 kernel in CAF having that patch, however - that may more be related to 3.4 being out of maintenance now.

In general, difficult. We may simply "trust/follow" the LOS maintainers having more experience than us and assume that it is not relevant or follow our own impression that it is necessary to patch.
(It has to be said many of the LOS device maintainers definitely are light years beyond our skills, but not all... - and since it is work, many are not really keen on patching the kernels, I have followed some discussions on the LOS slack forum, very interesting...) 

I'll try to have a deeper look . . .

**Comment by MSe1969** [comment]
Hi, 

I've succeeded to patched CVE-2016-5349 - after a couple of tries, it now compiles w/o syntax error finally... 

I've created a new branch **cve-2016-5349** for this exercise in the kernel repo. It contains the four commits linked to that CVE in the April 2017 ASB. Further, I've added a file CVE-2016-5349.txt to our discussion repo.

**I definitely need a 2nd opinion about this topic**, as the code differs significantly. I recommend the following approach: 
Look at the diff-view in CAF (as linked from the April ASB) for each of the commits nr 1, nr 2, nr 3 and nr 4 and compare with the respective commit's diff view in the cve-2016-5349 branch. You will see in the CVE-2016-5349.txt file my comments, why things look different / why I backported it this way.

I'll now flash the ROM and hope, that this thing would run stable . . .
Thanks, M.

**Comment by MSe1969** [comment]
Seems to run stable so far - nevertheless, I really need your input

**Comment by Micha-Btz** [comment]
for me it looks quite good but I would prefer if @hahnjo can also take a look.

**Comment by Micha-Btz** [comment]
I would merge the cm-12.1-test branch to cm-12.1 so that we can start with July ASB.
Should I also merge CVE-2016-5349? Or should we test this one a little bit more?

**Comment by MSe1969** [comment]
I suggest the following:
1. Merge the current cm-12.1 branch into a new 'backup' branch first (just in case - we can purge later)
2. Merge cve-2016-5349 into cm-12.1-test first and then cm-12.1-test into cm-12.1
(I haven't observed any misbehavior, but I still would like @hahnjo to have a look)

**Comment by Micha-Btz** [comment]
make sense

**Comment by Micha-Btz** [comment]
I think we are ready for release and the kernel is now on the latest patch level. So I think we can close this.

**Comment by hahnjo** [comment]
Sorry for the late reply but I'have been really busy in the past weeks...

@MSe1969 The applied patches look good from a short glimpse. Even if they don't fix the problem in the worst case, it's still better than nothing ;-)

I agree, this should be ready for release with the current ASB!
